version: '3.8'

services:
  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      # MongoDB Configuration
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_MIN_POOL_SIZE=5
      - MONGODB_MAX_POOL_SIZE=10
      - MONGODB_RETRY_ATTEMPTS=3
      - MONGODB_RETRY_DELAY=1000
      - MONGODB_MONITORING_ENABLED=true
      # JWT Configuration
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=1h
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - JWT_REFRESH_EXPIRATION=7d
      # SMTP Configuration
      - SMTP_FROM=${SMTP_FROM}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      # Application URL
      - APP_URL=http://localhost:3001/api
    networks:
      - marketplace-network

networks:
  marketplace-network:
    driver: bridge
